### ISSUE TITLE
Impossible de télécharger le jeu

### ISSUE THREAD

**Issue by Aleqsd** [o3LL/zzccmxtp#14]
Yo, le captcha est broken sur https://zzcc.fr/telechargement (je sais pas si ça fait partie de ton scope ou pas)

**Comment by o3LL** [comment]
C pas mon site ça mais tu peux le télécharger sur zzccmxtp.fr si tu cherche bien hehe

**Comment by Aleqsd** [comment]
> C pas mon site ça mais tu peux le télécharger sur zzccmxtp.fr si tu cherche bien hehe

Ah ui trop bien j'ai trouvé
Pour ceux qui chercheraient https://s3.eu-west-1.amazonaws.com/zzccmxtp.fr/zzcclalegendre.rar

merci mec
